# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python program into the container
COPY . .

# Set the command to run your Python program
CMD [ "python3", "hangman.py" ]
